# Generated by Django 2.1.5 on 2019-01-18 17:15

from django.db import migrations, models
import django.db.models.deletion
import studentDatabase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=100)),
                ('student_school_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('student_identification_certificate_number', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=3)),
                ('student_homeroom', models.CharField(max_length=50)),
                ('student_sibling_number', models.IntegerField()),
                ('student_sibling_total', models.IntegerField()),
                ('student_nationality', models.CharField(choices=[('MALAY', 'MALAY'), ('CHINESE', 'CHINESE'), ('INDIAN', 'INDIAN'), ('OTHERS', 'OTHERS')], default='MALAY', max_length=50)),
                ('student_date_of_birth', models.DateField()),
                ('student_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('student_religion', models.CharField(choices=[('MUSLIM', 'MUSLIM'), ('BUDDHIST', 'BUDDHIST'), ('CHRISTIAN', 'CHRISTIAN'), ('ATHEIST', 'ATHEIST')], max_length=50)),
                ('student_photo', models.ImageField(upload_to=studentDatabase.models.Student.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=50)),
                ('father_income', models.IntegerField()),
                ('father_marital_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('DIVORCED', 'DIVORCED')], default='MARRIED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_income', models.IntegerField()),
                ('mother_marital_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('DIVORCED', 'DIVORCED')], default='MARRIED', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentDatabase.StudentFather'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentDatabase.StudentMother'),
        ),
    ]
